name: "Install Dependencies"
description: "Install vcpkg libraries and qt environment"
inputs:
  qt_modules:
    description: "qt modules"
    required: false
    default: "qt5compat qtnetworkauth qtmultimedia qtimageformats"
    type: string
  qt_ver:
    description: "qt version"
    required: false
    default: "6.10.1"
    type: string

runs:
  using: "composite"

  steps:
    - name: Install Custom VCPKG
      uses: RealChuan/install-vcpkg@main

    - name: Update vcpkg manifest baseline
      shell: bash
      run: |
        vcpkg x-update-baseline

    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build/vcpkg_installed
        key: ${{ runner.os }}-vcpkg-installed-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-
          ${{ runner.os }}-

    - name: Install dependencies on windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install ninja
        ninja --version
        cmake --version

    - name: Install dependencies on macos
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install nasm mpv
        ninja --version
        cmake --version
        clang --version

    - name: Install dependencies on linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build nasm autopoint gperf libgl1-mesa-dev \
            libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev libltdl-dev \
            autoconf autoconf-archive automake libtoolize \
            mpv libmpv-dev
        ninja --version
        cmake --version
        gcc --version

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt_ver }}
        modules: ${{ inputs.qt_modules }}
        cache: "true"
